[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
stock_exchange = "EXJea2kQk2wQknjnAxVNhNfyrVC6YwAM653Ztx5C9Dj4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
